-- 1. Tabla de Disponibilidad Semanal (Horario Base)
CREATE TABLE public.user_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6), -- 0=Domingo, 1=Lunes...
    start_time TIME NOT NULL, -- ej. '08:00'
    end_time TIME NOT NULL,   -- ej. '19:00'
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, day_of_week)
);

-- 2. Tabla de Excepciones y Bloqueos de Disponibilidad
CREATE TABLE public.user_availability_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    specific_date DATE NOT NULL,
    is_off_day BOOLEAN DEFAULT false, -- Si es true, todo el día está bloqueado (feriado, vacaciones)
    start_time TIME, -- Si is_off_day es false, define un horario especial para ese día específico
    end_time TIME,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, specific_date)
);

-- 3. Tabla de Citas (Appointments)
CREATE TABLE public.appointments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    lead_id UUID REFERENCES public.leads(id) ON DELETE CASCADE,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL, -- Generalmente start_time + 45mins
    status TEXT NOT NULL DEFAULT 'agendada' CHECK (status IN ('agendada', 'cancelada', 'completada')),
    google_event_id TEXT,
    meet_link TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.user_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_availability_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 5. Crear Políticas (Policies)
CREATE POLICY "Users can view their own availability" ON public.user_availability FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own availability" ON public.user_availability FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own availability" ON public.user_availability FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own availability" ON public.user_availability FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own overrides" ON public.user_availability_overrides FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own overrides" ON public.user_availability_overrides FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own overrides" ON public.user_availability_overrides FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own overrides" ON public.user_availability_overrides FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own appointments" ON public.appointments FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own appointments" ON public.appointments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own appointments" ON public.appointments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own appointments" ON public.appointments FOR DELETE USING (auth.uid() = user_id);

-- 6. Habilitar WebSockets (Realtime)
alter publication supabase_realtime add table public.appointments;

-- 7. Función RPC para calcular disponibilidad (Endpoint ultrarrápido)
-- Esta función genera bloques de 1 hora (45m reunión + 15m descanso)
CREATE OR REPLACE FUNCTION get_available_slots(p_user_id UUID, p_start_date DATE, p_days INTEGER)
RETURNS TABLE (
    slot_date DATE,
    starts_at TIMESTAMP WITH TIME ZONE,
    disabled BOOLEAN
) AS $$
DECLARE
    current_date_iter DATE := p_start_date;
    end_date DATE := p_start_date + p_days - 1;
    v_day_of_week INTEGER;
    v_start_time TIME;
    v_end_time TIME;
    v_is_off BOOLEAN;
    v_current_slot TIMESTAMP WITH TIME ZONE;
    v_slot_end TIMESTAMP WITH TIME ZONE;
    v_conflict_count INTEGER;
BEGIN
    WHILE current_date_iter <= end_date LOOP
        -- Verificar si hay una excepción/bloqueo para esta fecha
        SELECT is_off_day, start_time, end_time INTO v_is_off, v_start_time, v_end_time
        FROM public.user_availability_overrides
        WHERE user_id = p_user_id AND specific_date = current_date_iter;

        IF NOT FOUND THEN
            -- Si no hay excepción, buscar el horario base semanal
            v_day_of_week := EXTRACT(DOW FROM current_date_iter);
            SELECT start_time, end_time INTO v_start_time, v_end_time
            FROM public.user_availability
            WHERE user_id = p_user_id AND day_of_week = v_day_of_week AND is_active = true;
            
            v_is_off := NOT FOUND;
        END IF;

        IF NOT v_is_off THEN
            -- Generar bloques de 1 hora dentro de la ventana de disponibilidad
            v_current_slot := current_date_iter + v_start_time;
            
            WHILE (v_current_slot + interval '1 hour')::time <= v_end_time LOOP
                v_slot_end := v_current_slot + interval '45 minutes';
                
                -- Chequear si ya hay una cita (appointment) que se superpone con este bloque
                SELECT count(*) INTO v_conflict_count
                FROM public.appointments
                WHERE user_id = p_user_id 
                AND status = 'agendada'
                AND start_time < (v_current_slot + interval '1 hour')
                AND end_time > v_current_slot;

                RETURN QUERY SELECT 
                    current_date_iter, 
                    v_current_slot, 
                    (v_conflict_count > 0) OR (v_current_slot < timezone('utc'::text, now()));
                
                v_current_slot := v_current_slot + interval '1 hour';
            END LOOP;
        END IF;

        current_date_iter := current_date_iter + 1;
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
