-- 1. Crear tabla para las categorías/listas de plantillas
CREATE TABLE public.template_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('whatsapp', 'email', 'call')),
    name TEXT NOT NULL,
    color TEXT DEFAULT '#3B82F6',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.template_lists ENABLE ROW LEVEL SECURITY;

-- 3. Crear Políticas (Policies)
CREATE POLICY "Usuarios ven sus propias categorias de plantillas" ON public.template_lists FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Usuarios insertan sus propias categorias de plantillas" ON public.template_lists FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Usuarios actualizan sus propias categorias de plantillas" ON public.template_lists FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Usuarios borran sus propias categorias de plantillas" ON public.template_lists FOR DELETE USING (auth.uid() = user_id);

-- 4. Habilitar Realtime
alter publication supabase_realtime add table public.template_lists;
