-- Query permanente
-- Dominio: lead
-- Objetivo: crear notas de lead y registro de envios

CREATE TABLE IF NOT EXISTS public.lead_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.lead_notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios gestionan sus propias notas" ON public.lead_notes;
CREATE POLICY "Usuarios gestionan sus propias notas"
ON public.lead_notes
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.send_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  template_id uuid REFERENCES public.templates(id) ON DELETE SET NULL,
  template_type text NOT NULL,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  lead_name text,
  lead_phone text,
  sent_at timestamptz DEFAULT now(),
  scheduled_for timestamptz
);

ALTER TABLE public.send_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios ven sus propios envios" ON public.send_logs;
CREATE POLICY "Usuarios ven sus propios envios"
ON public.send_logs
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
