-- Query permanente
-- Dominio: agenda
-- Objetivo: crear disponibilidad, appointments y RPC de slots

CREATE TABLE IF NOT EXISTS public.user_availability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time NOT NULL,
  end_time time NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, day_of_week)
);

CREATE TABLE IF NOT EXISTS public.user_availability_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  specific_date date NOT NULL,
  is_off_day boolean DEFAULT false,
  start_time time,
  end_time time,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, specific_date)
);

CREATE TABLE IF NOT EXISTS public.appointments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'agendada' CHECK (status IN ('agendada', 'cancelada', 'completada')),
  google_event_id text,
  meet_link text,
  notes text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.user_availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_availability_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own availability" ON public.user_availability;
CREATE POLICY "Users can view their own availability"
ON public.user_availability
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own availability" ON public.user_availability;
CREATE POLICY "Users can insert their own availability"
ON public.user_availability
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own availability" ON public.user_availability;
CREATE POLICY "Users can update their own availability"
ON public.user_availability
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own availability" ON public.user_availability;
CREATE POLICY "Users can delete their own availability"
ON public.user_availability
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own overrides" ON public.user_availability_overrides;
CREATE POLICY "Users can view their own overrides"
ON public.user_availability_overrides
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own overrides" ON public.user_availability_overrides;
CREATE POLICY "Users can insert their own overrides"
ON public.user_availability_overrides
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own overrides" ON public.user_availability_overrides;
CREATE POLICY "Users can update their own overrides"
ON public.user_availability_overrides
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own overrides" ON public.user_availability_overrides;
CREATE POLICY "Users can delete their own overrides"
ON public.user_availability_overrides
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view their own appointments" ON public.appointments;
CREATE POLICY "Users can view their own appointments"
ON public.appointments
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own appointments" ON public.appointments;
CREATE POLICY "Users can insert their own appointments"
ON public.appointments
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own appointments" ON public.appointments;
CREATE POLICY "Users can update their own appointments"
ON public.appointments
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own appointments" ON public.appointments;
CREATE POLICY "Users can delete their own appointments"
ON public.appointments
FOR DELETE
USING (auth.uid() = user_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'appointments'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.appointments';
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.get_available_slots(p_user_id uuid, p_start_date date, p_days integer)
RETURNS TABLE (
  slot_date date,
  starts_at timestamptz,
  disabled boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_date_iter date := p_start_date;
  end_date date := p_start_date + p_days - 1;
  v_day_of_week integer;
  v_start_time time;
  v_end_time time;
  v_is_off boolean;
  v_current_slot timestamptz;
  v_conflict_count integer;
BEGIN
  WHILE current_date_iter <= end_date LOOP
    SELECT is_off_day, start_time, end_time
    INTO v_is_off, v_start_time, v_end_time
    FROM public.user_availability_overrides
    WHERE user_id = p_user_id
      AND specific_date = current_date_iter;

    IF NOT FOUND THEN
      v_day_of_week := EXTRACT(DOW FROM current_date_iter);
      SELECT start_time, end_time
      INTO v_start_time, v_end_time
      FROM public.user_availability
      WHERE user_id = p_user_id
        AND day_of_week = v_day_of_week
        AND is_active = true;

      v_is_off := NOT FOUND;
    END IF;

    IF NOT v_is_off THEN
      v_current_slot := current_date_iter + v_start_time;

      WHILE (v_current_slot + interval '1 hour')::time <= v_end_time LOOP
        SELECT count(*) INTO v_conflict_count
        FROM public.appointments
        WHERE user_id = p_user_id
          AND status = 'agendada'
          AND start_time < (v_current_slot + interval '1 hour')
          AND end_time > v_current_slot;

        RETURN QUERY
        SELECT
          current_date_iter,
          v_current_slot,
          (v_conflict_count > 0) OR (v_current_slot < timezone('utc'::text, now()));

        v_current_slot := v_current_slot + interval '1 hour';
      END LOOP;
    END IF;

    current_date_iter := current_date_iter + 1;
  END LOOP;
END;
$$;
