-- message_reasons
--
-- Tipo:           query permanente (tabla nueva + columna nueva)
-- Objeto:         public.message_reasons, public.templates
-- Clase:          capacidad nueva
-- Persistencia:   permanente
-- Reversibilidad: total (drop de la columna y de la tabla)
--
-- PROPOSITO
--
-- Catalogo de motivos para la variable `{motivo}` de las plantillas:
--
--   "Hola, {nombre}. Te escribo porque {motivo}."
--
-- Hasta hoy `{motivo}` no existia como variable, asi que una plantilla que lo
-- usara enviaba el texto con las llaves puestas. Ya hay al menos una plantilla
-- del usuario en ese estado ("WS Cold #1").
--
-- POR QUE EL VALOR NO VIVE EN LA PLANTILLA
--
-- La tentacion es una columna `reason` en `templates`. Pero entonces cada motivo
-- exige su propia plantilla, y `{motivo}` deja de ahorrar nada: seria escribir el
-- texto directo con un rodeo. El valor de la variable esta en que **una plantilla
-- sirva para muchos motivos**.
--
-- Lo que si vive en la plantilla es un **valor por defecto**: se elige al
-- crearla, viene prellenado al enviar, y se puede cambiar en cada envio. Eso da
-- la comodidad sin la atadura.
--
-- POR QUE UNA TABLA PROPIA Y NO `metadata`
--
-- El motivo se elige de una lista cerrada que el usuario administra, se muestra
-- en un desplegable y se referencia desde plantillas. Es una entidad, no un
-- atributo suelto.
--
-- UN SOLO CAMPO DE TEXTO
--
-- El motivo es la frase que sustituye al token, y esa misma frase es la que se
-- lee en el desplegable. Separar "etiqueta corta" de "texto largo" seria un
-- campo mas que rellenar para un catalogo que el usuario describio como "una
-- lista de motivos". Si algun dia las frases se alargan tanto que el desplegable
-- se vuelve ilegible, agregar la etiqueta es aditivo.
--
-- OJO CON EL NOMBRE
--
-- `leads.discard_reason` (migracion 100) tambien se llama "motivo" en pantalla,
-- pero es otra cosa: por que se descarto un lead. Son dominios distintos y no
-- deben mezclarse. En la interfaz este se llama "motivo del mensaje".

create table if not exists public.message_reasons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (length(trim(text)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.message_reasons is
  'Catalogo de motivos que sustituyen la variable {motivo} de las plantillas. Distinto de leads.discard_reason, que es el motivo por el que se descarta un lead.';

create index if not exists message_reasons_user_id_idx
  on public.message_reasons (user_id, created_at desc);

alter table public.message_reasons enable row level security;

drop policy if exists "message_reasons_select_own" on public.message_reasons;
create policy "message_reasons_select_own" on public.message_reasons
  for select using (auth.uid() = user_id);

drop policy if exists "message_reasons_insert_own" on public.message_reasons;
create policy "message_reasons_insert_own" on public.message_reasons
  for insert with check (auth.uid() = user_id);

drop policy if exists "message_reasons_update_own" on public.message_reasons;
create policy "message_reasons_update_own" on public.message_reasons
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "message_reasons_delete_own" on public.message_reasons;
create policy "message_reasons_delete_own" on public.message_reasons
  for delete using (auth.uid() = user_id);

-- Valor prellenado de la plantilla. `set null` y no `restrict`: borrar un motivo
-- solo debe quitar el prellenado, nunca impedir borrarlo ni romper la plantilla.
alter table public.templates
  add column if not exists default_reason_id bigint
    references public.message_reasons(id) on delete set null;

comment on column public.templates.default_reason_id is
  'Motivo que viene prellenado al enviar esta plantilla. Es un valor por defecto, no una atadura: se puede cambiar en cada envio.';

-- REVERSION
--
--   alter table public.templates drop column if exists default_reason_id;
--   drop table if exists public.message_reasons;
