-- message_flows
--
-- Tipo:           query permanente (tablas nuevas + trigger)
-- Objeto:         public.message_flows, message_flow_steps,
--                 message_flow_enrollments, message_flow_progress
-- Clase:          capacidad nueva
-- Persistencia:   permanente
-- Reversibilidad: total (drop de las cuatro tablas y del trigger)
--
-- PROPOSITO
--
-- Secuencias de mensajes con seguimiento por lead: en que paso va cada uno, que
-- falta por enviar, quien entra y quien sale.
--
-- LO QUE EL SISTEMA PUEDE SABER, Y LO QUE NO
--
-- Esto condiciona el modelo entero, asi que va antes que el DDL:
--
--   * WhatsApp se envia **abriendo una URL**. La aplicacion no sabe si el
--     mensaje salio, llego o se leyo. Solo sabe que se hizo clic.
--   * El correo si sale de verdad, pero no hay webhook de Resend: "enviado"
--     significa que la llamada a la API no fallo.
--   * **No existe canal entrante.** Las respuestas de un lead no se registran en
--     ninguna tabla del proyecto.
--
-- Por eso el estado de un paso se llama `registrado` y no `enviado`, y por eso
-- no hay ramificacion condicional: "si no respondio en tres dias" no es
-- detectable, seria inventar una señal que no existe.
--
-- DECISIONES QUE NO SE LEEN DEL DDL
--
-- **Los flujos son por canal.** Un lead puede estar a la vez en un flujo de
-- WhatsApp, uno de correo y uno de llamada, pero no en dos del mismo canal. Es
-- lo que pidio el usuario y encaja con el resto: las plantillas ya son por canal.
-- El indice unico parcial de `message_flow_enrollments` es quien lo garantiza.
--
-- **El progreso tiene tabla propia y no se deduce de `send_logs`.** Tentador,
-- porque ahi esta lo que se mando, pero `send_logs` no tiene referencia al
-- flujo: un envio suelto de la misma plantilla contaria como paso completado, y
-- la misma plantilla en dos flujos contaria dos veces. Ademas no habria donde
-- expresar **cuando toca** el siguiente paso, que es justo lo que el usuario
-- quiere ver. La fila de progreso no copia lo enviado: apunta a `send_logs` con
-- `send_log_id`, asi que sigue habiendo un solo registro de envios.
--
-- **Las tablas hijas llevan `user_id` propio, puesto por un trigger.** Una clave
-- foranea no impide insertar un paso cuyo `flow_id` apunta al flujo de otro
-- usuario: la RLS se pasa con el `user_id` propio y la FK solo exige que el
-- flujo exista. El trigger lo copia del padre y nunca confia en el cliente.
--
-- **Reinscribir crea una fila nueva, no reabre la vieja.** Un flujo que se
-- reinicia recorre la secuencia entera; continuar donde quedo un intento
-- anterior mezclaria dos historias. El indice unico es parcial (`where status =
-- 'activa'`) justamente para permitir el historial de intentos.
--
-- **Borrar un paso esta prohibido si tiene progreso** (`on delete restrict` en
-- `message_flow_progress.step_id`). Perder el rastro de lo que se envio para
-- limpiar una definicion es el peor intercambio posible.

-- ---------------------------------------------------------------- FLUJOS

create table if not exists public.message_flows (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('whatsapp', 'email', 'call')),
  name text not null check (length(trim(name)) > 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.message_flows is
  'Secuencia de mensajes de un canal. Un lead puede estar en un flujo por canal, no en dos del mismo.';

create index if not exists message_flows_user_channel_idx
  on public.message_flows (user_id, channel, created_at desc);

-- ----------------------------------------------------------------- PASOS

create table if not exists public.message_flow_steps (
  id bigint generated by default as identity primary key,
  flow_id uuid not null references public.message_flows(id) on delete cascade,
  user_id uuid not null,
  step_order integer not null check (step_order > 0),
  template_id uuid not null references public.templates(id) on delete restrict,
  -- Espera desde que se registro el paso anterior. Cero = disponible enseguida.
  wait_days integer not null default 0 check (wait_days >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (flow_id, step_order)
);

comment on column public.message_flow_steps.template_id is
  'on delete restrict a proposito: una plantilla borrada dejaria el paso roto en silencio. Mejor que el borrado falle con un error claro.';

create index if not exists message_flow_steps_flow_idx on public.message_flow_steps (flow_id, step_order);
create index if not exists message_flow_steps_user_idx on public.message_flow_steps (user_id);

-- --------------------------------------------------------- INSCRIPCIONES

create table if not exists public.message_flow_enrollments (
  id bigint generated by default as identity primary key,
  flow_id uuid not null references public.message_flows(id) on delete cascade,
  user_id uuid not null,
  lead_id uuid not null references public.leads(id) on delete cascade,
  -- Se copia del flujo para poder exigir "una activa por lead y canal" sin
  -- unir contra el padre en un indice, cosa que Postgres no permite.
  channel text not null check (channel in ('whatsapp', 'email', 'call')),
  status text not null default 'activa' check (status in ('activa', 'completada', 'salida')),
  enrolled_at timestamptz not null default now(),
  exited_at timestamptz,
  exit_reason text check (exit_reason in (
    'convertido', 'descartado', 'fin_secuencia', 'respondio', 'manual', 'otro_flujo'
  )),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Un lead, un flujo activo por canal. Parcial para permitir reinscribir.
create unique index if not exists message_flow_enrollments_una_activa_por_canal_idx
  on public.message_flow_enrollments (lead_id, channel)
  where status = 'activa';

create index if not exists message_flow_enrollments_flow_idx
  on public.message_flow_enrollments (flow_id, status);
create index if not exists message_flow_enrollments_user_lead_idx
  on public.message_flow_enrollments (user_id, lead_id);

-- ---------------------------------------------------------- PROGRESO

create table if not exists public.message_flow_progress (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references public.message_flow_enrollments(id) on delete cascade,
  step_id bigint not null references public.message_flow_steps(id) on delete restrict,
  user_id uuid not null,
  -- `registrado`, no `enviado`: con WhatsApp solo consta que se abrio el chat.
  status text not null default 'pendiente' check (status in (
    'pendiente', 'toca', 'registrado', 'omitido', 'fallido'
  )),
  due_at timestamptz,
  dispatched_at timestamptz,
  send_log_id bigint references public.send_logs(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (enrollment_id, step_id)
);

comment on column public.message_flow_progress.status is
  'registrado significa que se registro la accion del canal, no que el lead lo recibiera. Con WhatsApp la aplicacion solo sabe que se abrio el chat.';

comment on column public.message_flow_progress.send_log_id is
  'Apunta al registro de envio en vez de copiarlo: send_logs sigue siendo el unico registro de lo que se mando.';

-- Lo que alimenta la vista "que falta enviar hoy".
create index if not exists message_flow_progress_pendiente_idx
  on public.message_flow_progress (user_id, due_at)
  where status in ('pendiente', 'toca');

create index if not exists message_flow_progress_enrollment_idx
  on public.message_flow_progress (enrollment_id);

-- --------------------------------------- user_id de las hijas, por trigger

/*
 * Copia el dueño desde el flujo padre.
 *
 * Sin esto, una FK no basta: se puede insertar un paso con el `user_id` propio
 * -que pasa la RLS- y un `flow_id` que apunta al flujo de otro usuario, porque
 * la FK solo comprueba que el flujo exista, no de quien es.
 */
create or replace function public.message_flow_hija_hereda_dueno()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_channel text;
begin
  if tg_table_name = 'message_flow_progress' then
    select e.user_id into v_user_id
    from public.message_flow_enrollments e
    where e.id = new.enrollment_id;

    if v_user_id is null then
      raise exception 'la inscripcion % no existe', new.enrollment_id;
    end if;
  else
    select f.user_id, f.channel into v_user_id, v_channel
    from public.message_flows f
    where f.id = new.flow_id;

    if v_user_id is null then
      raise exception 'el flujo % no existe', new.flow_id;
    end if;

    -- El canal tampoco se acepta del cliente: sale del flujo.
    if tg_table_name = 'message_flow_enrollments' then
      new.channel := v_channel;
    end if;
  end if;

  new.user_id := v_user_id;
  return new;
end;
$$;

drop trigger if exists message_flow_steps_dueno on public.message_flow_steps;
create trigger message_flow_steps_dueno
  before insert or update of flow_id on public.message_flow_steps
  for each row execute function public.message_flow_hija_hereda_dueno();

drop trigger if exists message_flow_enrollments_dueno on public.message_flow_enrollments;
create trigger message_flow_enrollments_dueno
  before insert or update of flow_id on public.message_flow_enrollments
  for each row execute function public.message_flow_hija_hereda_dueno();

drop trigger if exists message_flow_progress_dueno on public.message_flow_progress;
create trigger message_flow_progress_dueno
  before insert or update of enrollment_id on public.message_flow_progress
  for each row execute function public.message_flow_hija_hereda_dueno();

-- --------------------------------------------------------------- RLS

alter table public.message_flows enable row level security;
alter table public.message_flow_steps enable row level security;
alter table public.message_flow_enrollments enable row level security;
alter table public.message_flow_progress enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'message_flows', 'message_flow_steps',
    'message_flow_enrollments', 'message_flow_progress'
  ] loop
    execute format('drop policy if exists "%1$s_select_own" on public.%1$s', t);
    execute format(
      'create policy "%1$s_select_own" on public.%1$s for select using (auth.uid() = user_id)', t);

    execute format('drop policy if exists "%1$s_insert_own" on public.%1$s', t);
    execute format(
      'create policy "%1$s_insert_own" on public.%1$s for insert with check (auth.uid() = user_id)', t);

    execute format('drop policy if exists "%1$s_update_own" on public.%1$s', t);
    execute format(
      'create policy "%1$s_update_own" on public.%1$s for update using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);

    execute format('drop policy if exists "%1$s_delete_own" on public.%1$s', t);
    execute format(
      'create policy "%1$s_delete_own" on public.%1$s for delete using (auth.uid() = user_id)', t);
  end loop;
end
$$;

-- REVERSION
--
--   drop table if exists public.message_flow_progress;
--   drop table if exists public.message_flow_enrollments;
--   drop table if exists public.message_flow_steps;
--   drop table if exists public.message_flows;
--   drop function if exists public.message_flow_hija_hereda_dueno();
