-- Query permanente
-- Dominio: crm / saas / realtime
-- Objetivo: crear el nucleo base del CRM y del catalogo SaaS con RLS inicial

CREATE TABLE IF NOT EXISTS public.leads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text,
  email text,
  company text,
  rut text,
  status text DEFAULT 'nuevo',
  score integer DEFAULT 0,
  lista_ids integer[] DEFAULT '{}'::integer[],
  notes text,
  scheduled_at timestamptz,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  assigned_at timestamptz DEFAULT timezone('utc'::text, now()),
  first_contacted_at timestamptz,
  closed_at timestamptz,
  estimated_value numeric DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  deleted_at timestamptz,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  status text DEFAULT 'pendiente',
  due_date timestamptz,
  lead_list_ids integer[] DEFAULT '{}'::integer[],
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.lead_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  color text DEFAULT '#3b82f6',
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.templates (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  name text NOT NULL,
  content text,
  subject text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.internal_messages (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  receiver_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  context_req_id uuid,
  context_ticket_code text,
  context_ticket_type text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.plans (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.features (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  trial_days integer DEFAULT 0,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.plan_features (
  plan_id text REFERENCES public.plans(id) ON DELETE CASCADE,
  feature_id text REFERENCES public.features(id) ON DELETE CASCADE,
  PRIMARY KEY (plan_id, feature_id)
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  role text DEFAULT 'user',
  is_helper boolean DEFAULT false,
  plan_id text REFERENCES public.plans(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_feature_overrides (
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  feature_id text REFERENCES public.features(id) ON DELETE CASCADE,
  expires_at timestamptz,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (user_id, feature_id)
);

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_feature_overrides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios ven sus propios leads" ON public.leads;
CREATE POLICY "Usuarios ven sus propios leads"
ON public.leads
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios insertan sus leads" ON public.leads;
CREATE POLICY "Usuarios insertan sus leads"
ON public.leads
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios actualizan sus leads" ON public.leads;
CREATE POLICY "Usuarios actualizan sus leads"
ON public.leads
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios borran sus leads" ON public.leads;
CREATE POLICY "Usuarios borran sus leads"
ON public.leads
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios ven sus tareas" ON public.tasks;
CREATE POLICY "Usuarios ven sus tareas"
ON public.tasks
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios insertan sus tareas" ON public.tasks;
CREATE POLICY "Usuarios insertan sus tareas"
ON public.tasks
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios actualizan sus tareas" ON public.tasks;
CREATE POLICY "Usuarios actualizan sus tareas"
ON public.tasks
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios borran sus tareas" ON public.tasks;
CREATE POLICY "Usuarios borran sus tareas"
ON public.tasks
FOR DELETE
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios gestionan sus propias lead lists" ON public.lead_lists;
CREATE POLICY "Usuarios gestionan sus propias lead lists"
ON public.lead_lists
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios gestionan sus propios templates" ON public.templates;
CREATE POLICY "Usuarios gestionan sus propios templates"
ON public.templates
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.profiles;
CREATE POLICY "Authenticated users can read profiles"
ON public.profiles
FOR SELECT
USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Public Read Plans" ON public.plans;
DROP POLICY IF EXISTS "Leer planes" ON public.plans;
CREATE POLICY "Public Read Plans"
ON public.plans
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public Read Features" ON public.features;
DROP POLICY IF EXISTS "Leer features" ON public.features;
CREATE POLICY "Public Read Features"
ON public.features
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public Read Plan Features" ON public.plan_features;
DROP POLICY IF EXISTS "Leer plan_features" ON public.plan_features;
CREATE POLICY "Public Read Plan Features"
ON public.plan_features
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "User Read Overrides" ON public.user_feature_overrides;
DROP POLICY IF EXISTS "Usuario lee sus overrides" ON public.user_feature_overrides;
CREATE POLICY "User Read Overrides"
ON public.user_feature_overrides
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Ver mensajes internos propios o publicos" ON public.internal_messages;
CREATE POLICY "Ver mensajes internos propios o publicos"
ON public.internal_messages
FOR SELECT
USING (
  receiver_id IS NULL
  OR sender_id = auth.uid()
  OR receiver_id = auth.uid()
  OR EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (p.role = 'admin' OR coalesce(p.is_helper, false) = true)
  )
);

DROP POLICY IF EXISTS "Enviar mensajes internos a nombre propio" ON public.internal_messages;
CREATE POLICY "Enviar mensajes internos a nombre propio"
ON public.internal_messages
FOR INSERT
WITH CHECK (sender_id = auth.uid());

DROP POLICY IF EXISTS "Actualizar lectura de mensajes internos" ON public.internal_messages;
CREATE POLICY "Actualizar lectura de mensajes internos"
ON public.internal_messages
FOR UPDATE
USING (
  sender_id = auth.uid()
  OR receiver_id = auth.uid()
  OR EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (p.role = 'admin' OR coalesce(p.is_helper, false) = true)
  )
)
WITH CHECK (
  sender_id = auth.uid()
  OR receiver_id = auth.uid()
  OR EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (p.role = 'admin' OR coalesce(p.is_helper, false) = true)
  )
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'leads'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.leads';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'tasks'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'internal_messages'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.internal_messages';
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
