-- Query permanente
-- Dominio: planespro_agenda / Google Calendar
-- Objetivo: permitir sincronizacion de ocupacion Google como bloqueos no editables por UI

ALTER TABLE public.user_availability_blocks
ADD COLUMN IF NOT EXISTS google_event_id text,
ADD COLUMN IF NOT EXISTS google_calendar_id text,
ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS user_availability_blocks_google_idx
ON public.user_availability_blocks (user_id, google_calendar_id, google_event_id)
WHERE block_type = 'google' AND google_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS user_availability_blocks_google_range_idx
ON public.user_availability_blocks (user_id, starts_at, ends_at)
WHERE block_type = 'google';

COMMENT ON COLUMN public.user_availability_blocks.google_event_id IS
'Opaque Google Calendar busy slot identifier generated by sync. Not exposed as event details.';

COMMENT ON COLUMN public.user_availability_blocks.metadata IS
'Non-sensitive sync metadata. Do not store Google access or refresh tokens here.';
