-- Query permanente
-- Dominio: template
-- Objetivo: crear categorias de plantillas por tipo

CREATE TABLE IF NOT EXISTS public.template_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('whatsapp', 'email', 'call')),
  name text NOT NULL,
  color text DEFAULT '#3B82F6',
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.template_lists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios ven sus propias categorias de plantillas" ON public.template_lists;
CREATE POLICY "Usuarios ven sus propias categorias de plantillas"
ON public.template_lists
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios insertan sus propias categorias de plantillas" ON public.template_lists;
CREATE POLICY "Usuarios insertan sus propias categorias de plantillas"
ON public.template_lists
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios actualizan sus propias categorias de plantillas" ON public.template_lists;
CREATE POLICY "Usuarios actualizan sus propias categorias de plantillas"
ON public.template_lists
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Usuarios borran sus propias categorias de plantillas" ON public.template_lists;
CREATE POLICY "Usuarios borran sus propias categorias de plantillas"
ON public.template_lists
FOR DELETE
USING (auth.uid() = user_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'template_lists'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.template_lists';
  END IF;
END $$;
