-- Query permanente
-- Dominio: planespro / lead capture
-- Objetivo: recibir leads publicos de planespro.cl, resolver ownership comercial y enrutarlos al CRM actual

CREATE TABLE IF NOT EXISTS public.capture_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref_code text NOT NULL UNIQUE,
  label text,
  owner_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  advisor_id text,
  is_active boolean DEFAULT true NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS capture_links_owner_user_id_idx
ON public.capture_links (owner_user_id);

ALTER TABLE public.capture_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins and helpers can read capture links" ON public.capture_links;
CREATE POLICY "Admins and helpers can read capture links"
ON public.capture_links
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (p.role = 'admin' OR coalesce(p.is_helper, false) = true)
  )
);

DROP POLICY IF EXISTS "Admins can manage capture links" ON public.capture_links;
CREATE POLICY "Admins can manage capture links"
ON public.capture_links
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
  )
);

INSERT INTO storage.buckets (id, name, public)
VALUES ('planespro-form-uploads', 'planespro-form-uploads', false)
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.submit_planespro_public_lead(p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_name text := nullif(trim(coalesce(p_payload->>'name', p_payload->>'nombre', '')), '');
  v_phone text := nullif(trim(coalesce(p_payload->>'phone', p_payload->>'telefono', '')), '');
  v_email text := nullif(trim(coalesce(p_payload->>'email', p_payload->>'correo', '')), '');
  v_company text := nullif(trim(coalesce(p_payload->>'company', p_payload->>'empresa', '')), '');
  v_rut text := nullif(trim(coalesce(p_payload->>'rut', '')), '');
  v_notes text := nullif(trim(coalesce(
    p_payload->>'notes',
    p_payload->>'comentarios',
    p_payload->>'comentario',
    p_payload->>'message',
    p_payload->>'mensaje',
    ''
  )), '');
  v_capture_ref text := nullif(trim(coalesce(p_payload->>'capture_ref', p_payload->>'ref', '')), '');
  v_first_touch_ref text := nullif(trim(coalesce(p_payload->>'first_touch_ref', '')), '');
  v_contact_preference text := nullif(trim(coalesce(p_payload->>'contacto_preferencia', p_payload->>'contact_preference', '')), '');
  v_advisor_id text := nullif(trim(coalesce(p_payload->>'advisor_id', '')), '');
  v_pdf_path text := nullif(trim(coalesce(p_payload->>'pdf_path', p_payload->>'attachment_path', '')), '');
  v_appointment_at timestamptz := nullif(trim(coalesce(p_payload->>'cita_fecha_hora', p_payload->>'scheduled_at', '')), '')::timestamptz;
  v_appointment_status text := nullif(trim(coalesce(p_payload->>'cita_estado', '')), '');
  v_owner_user_id uuid;
  v_lead_id uuid;
BEGIN
  IF v_name IS NULL THEN
    RAISE EXCEPTION 'name is required';
  END IF;

  IF v_phone IS NULL AND v_email IS NULL THEN
    RAISE EXCEPTION 'phone or email is required';
  END IF;

  SELECT cl.owner_user_id
  INTO v_owner_user_id
  FROM public.capture_links cl
  WHERE cl.is_active = true
    AND cl.ref_code = v_capture_ref
  LIMIT 1;

  IF v_owner_user_id IS NULL THEN
    SELECT cl.owner_user_id
    INTO v_owner_user_id
    FROM public.capture_links cl
    WHERE cl.is_active = true
      AND cl.ref_code = v_first_touch_ref
    LIMIT 1;
  END IF;

  IF v_owner_user_id IS NULL THEN
    SELECT p.id
    INTO v_owner_user_id
    FROM public.profiles p
    WHERE p.email = 'planespro.cl@gmail.com'
    LIMIT 1;
  END IF;

  IF v_owner_user_id IS NULL THEN
    SELECT p.id
    INTO v_owner_user_id
    FROM public.profiles p
    WHERE p.role = 'admin'
    ORDER BY p.created_at
    LIMIT 1;
  END IF;

  IF v_owner_user_id IS NULL THEN
    RAISE EXCEPTION 'no admin profile available to receive public lead';
  END IF;

  INSERT INTO public.leads (
    user_id,
    name,
    phone,
    email,
    company,
    rut,
    status,
    notes,
    scheduled_at,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    metadata,
    created_at,
    updated_at
  )
  VALUES (
    v_owner_user_id,
    v_name,
    v_phone,
    v_email,
    v_company,
    v_rut,
    'nuevo',
    v_notes,
    v_appointment_at,
    nullif(trim(coalesce(p_payload->>'utm_source', '')), ''),
    nullif(trim(coalesce(p_payload->>'utm_medium', '')), ''),
    nullif(trim(coalesce(p_payload->>'utm_campaign', '')), ''),
    nullif(trim(coalesce(p_payload->>'utm_term', '')), ''),
    nullif(trim(coalesce(p_payload->>'utm_content', '')), ''),
    jsonb_build_object(
      'source_system', 'planespro',
      'capture_ref', v_capture_ref,
      'first_touch_ref', v_first_touch_ref,
      'contact_preference', v_contact_preference,
      'advisor_id', v_advisor_id,
      'appointment_status', v_appointment_status,
      'pdf_path', v_pdf_path,
      'raw_payload', p_payload
    ),
    timezone('utc'::text, now()),
    timezone('utc'::text, now())
  )
  RETURNING id INTO v_lead_id;

  RETURN jsonb_build_object(
    'lead_id', v_lead_id,
    'assigned_user_id', v_owner_user_id,
    'status', 'created'
  );
END;
$$;

COMMENT ON FUNCTION public.submit_planespro_public_lead(jsonb) IS
'Recibe un payload publico de planespro.cl, resuelve ownership por capture_ref y crea el lead en el CRM.';

NOTIFY pgrst, 'reload schema';
