-- 1. Actualización de Plantillas (Bug Prioridad 1)
ALTER TABLE public.templates ADD COLUMN IF NOT EXISTS is_html boolean DEFAULT false;

-- 2. Migración de Listas a la nube (Prioridad 2)
CREATE TABLE IF NOT EXISTS public.lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  color text DEFAULT '#3b82f6',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- RLS para lists
ALTER TABLE public.lists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios gestionan sus propias listas" ON public.lists
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 3. Migración de Notas de Leads a la nube
CREATE TABLE IF NOT EXISTS public.lead_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- RLS para lead_notes
ALTER TABLE public.lead_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios gestionan sus propias notas" ON public.lead_notes
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 4. Migración de Registro de Envíos (Send History) a la nube
CREATE TABLE IF NOT EXISTS public.send_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  template_id uuid REFERENCES public.templates(id) ON DELETE SET NULL,
  template_type text NOT NULL,
  lead_id uuid REFERENCES public.leads(id) ON DELETE CASCADE,
  lead_name text,
  lead_phone text,
  sent_at timestamptz DEFAULT now(),
  scheduled_for timestamptz
);

-- RLS para send_logs
ALTER TABLE public.send_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios ven sus propios envios" ON public.send_logs
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- 5. Migración de Preferencias y Settings de Usuario (al Profile existente)
ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS compact_mode boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS dark_mode boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS visible_cols jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS email_provider text DEFAULT 'emailjs',
  ADD COLUMN IF NOT EXISTS resend_api_key text,
  ADD COLUMN IF NOT EXISTS resend_from_name text,
  ADD COLUMN IF NOT EXISTS resend_from_email text,
  ADD COLUMN IF NOT EXISTS export_format text DEFAULT 'json',
  ADD COLUMN IF NOT EXISTS daily_goal_whatsapp integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS daily_goal_email integer DEFAULT 50,
  ADD COLUMN IF NOT EXISTS daily_goal_calls integer DEFAULT 20,
  ADD COLUMN IF NOT EXISTS dashboard_compare_period text DEFAULT 'yesterday';

-- (Opcional) Activar replicación en tiempo real para listas y notas si es necesario
-- ALTER PUBLICATION supabase_realtime ADD TABLE lists;
-- ALTER PUBLICATION supabase_realtime ADD TABLE lead_notes;
